# Generated by Django 5.1.1 on 2024-12-16 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_url', models.CharField(max_length=255)),
                ('score', models.IntegerField()),
                ('country', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('date_posted', models.CharField(max_length=255)),
                ('associated_item_url', models.CharField(max_length=255)),
            ],
        ),
    ]
