# Generated by Django 5.1.1 on 2024-12-16 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiroutes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='associated_item_url',
            new_name='associated_product_url',
        ),
    ]
