# Generated by Django 5.1.1 on 2024-12-16 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiroutes', '0002_rename_associated_item_url_review_associated_product_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associated_product_url', models.CharField(max_length=255)),
                ('review_country', models.TextField()),
                ('one_star_rating', models.IntegerField()),
                ('two_star_rating', models.IntegerField()),
                ('three_star_rating', models.IntegerField()),
                ('four_star_rating', models.IntegerField()),
                ('five_star_rating', models.IntegerField()),
                ('sentiment_analysis', models.TextField()),
                ('average_rating', models.FloatField()),
            ],
        ),
    ]
