# Generated by Django 5.1.1 on 2024-12-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiroutes', '0004_analysis_product_id_analysis_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='brand_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='brand_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='review',
            name='brand_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
